apiVersion: v1
kind: Service
metadata:
  name: ollama-chat-interface-service
spec:
  selector:
    app: ollama-chat-interface
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer