apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-chat-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-chat-interface
  template:
    metadata:
      labels:
        app: ollama-chat-interface
    spec:
      containers:
      - name: ollama-chat-interface
        image: ollama-chat-interface:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-chat-interface-service
spec:
  selector:
    app: ollama-chat-interface
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer